version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: { count: 1, period: hour }
          # gives a warning if we don't have any records within last hour
          error_after: { count: 24, period: hour }
          # gives an error if we don't have any records within last 24 hours
